### ISSUE TITLE
Support for multiple query parameters?

### ISSUE THREAD

**Issue by JannikZed** [nerdify/micro-query#1]
Hi,
I was trying to use your module but realized, that it just works for 1 query string. 
Doing stuff like this won't work unfortunately: `curl "http://localhost:3000?test1=zwei?test2=eins"`
It will give us an output like: `{ test1: 'zwei?test2=eins' }`.  
What we would expect as output:  
```
{ 
  test1: zwei,
  test2: eins
}
```

Should be not a big problem to implement it. I will also take a look into how to realize a correct behavior.

Kind regards

**Comment by hosmelq** [comment]
Hi @JannikZed i think your problem is because you have and extra `?` sign.

**Comment by JannikZed** [comment]
ah you are right! Thank you. It's working now.
